"""Evaluation 1 — the rules bank generated by openapi_rulesbank.

    official YAML ──extraction──▶ rules (rules-bank format) ─┐
                                                              ├─▶ comparison, rule by rule
    generated rules bank (JSON) ──────────────────────────────┘

rule_types.py  the definition of a rule: types, format, identity (rule_key)
extraction.py  official YAML → rules in the rules-bank format
comparison.py  extracted rules × generated bank, rule by rule

Pure logic: takes parsed documents, never reads files (that is services/).
"""
