"""Evaluation 2 — the OpenAPI document generated by openapi_generator.

    generated YAML ──┐
                     ├─▶ comparison, document against document
    official YAML  ──┘

comparison.py  generated YAML × official YAML

No rule extraction here: the two documents are compared directly.
Pure logic: takes parsed documents, never reads files (that is services/).
"""
