"""openapi_analysis — evaluate what the openapi_rulesbank and openapi_generator produce.

Two independent evaluations, both against the official 3GPP OpenAPI YAML:

  rules bank  rules extracted from the official YAML (in the rules-bank format)
              × the bank generated by openapi_rulesbank, compared rule by rule.
  openapi     the YAML generated by openapi_generator × the official YAML,
              compared document against document.

Layout: `rulesbank/` and `openapi/` hold the evaluation logic (pure, no I/O);
`services/` is what callers use (sibling repos, chat UI, CLI); `schemas/` defines
the reports; `reporting/` renders them; `api/` is the optional HTTP adapter.
"""

__version__ = "0.1.0"
